spring:
  application:
    name: user-provider
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      notify:
        slack:
          channel: app-health
          webhook-url: "https://hooks.slack.com/services/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"
          username: spring cloud admin
          message: "*#{application.name}* (#{application.id}) is *#{to.status}*"
server:
  port: 8080
eureka:
  client:
    service-url:
      #      defaultZone: http://registrar:7900/eureka/   #  docker环境用这个配置
      defaultZone: http://lisz:666@localhost:7900/eureka/
    healthcheck:
      enabled: true
  instance:
    metadata-map:
      dalao: lisz-hahaha
management:
  endpoints:
    web:
      # Actuator上报
      exposure:
        include: '*'
  endpoint:
    shutdown:
      # 调 Up/Down 状态
      enabled: true